--------------------------------------------------------------------------------
-- Company: hdlfactory.com
-- Engineer: Automated Assistant with Human Supervision
-- 
-- Create Date: Friday, June 19, 2026
-- Design Name: ethernet_top
-- Module Name: ethernet_top - rtl
-- Project Name: Gigabit Ethernet TEMAC loopback Test
-- Target Devices: xc7a200tfbg484-2 (Artix-7)
-- Tool Versions: Vivado 2025.2
-- 
-- Description: 
-- This is a top-level VHDL design that instantiates the Xilinx Tri-Mode
-- Ethernet MAC (TEMAC) IP and configures it in an end-to-end local digital loopback.
-- Packets received over the RGMII interface are deserialized, parsed by the MAC,
-- outputted on the rx_axis (AXI-Stream) interface, and immediately looped back
-- into the tx_axis (AXI-Stream) interface to be re-transmitted over RGMII.
--
-- Dependencies: 
-- - my_temac_core: Generated Tri-Mode Ethernet MAC IP
-- - PLLE2_BASE: Xilinx PLL clock generator primitive
-- - IDELAYCTRL: Xilinx tap calibration delay block controller primitive
-- 
-- Revision:
-- Revision 0.04 - Switched to deferred VHDL component instantiation for compile compatibility.
-- Additional Comments:
-- Copious comments describing the Top Level API elements have been added.
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- unisim library contains Xilinx device primitives like PLLE2_BASE and IDELAYCTRL
library unisim;
use unisim.vcomponents.all;

entity ethernet_top is
    port (
        ------------------------------------------------------------------------
        -- System Clock & Reset Inputs
        ------------------------------------------------------------------------
        clk          : in  std_logic; -- 100 MHz reference board clock input
        rst          : in  std_logic; -- 100 MHz board reset input

        ------------------------------------------------------------------------
        -- RGMII (Reduced Gigabit Medium Independent Interface) Physical Pins
        -- This interface connects directly to an external Gigabit Ethernet PHY
        -- (e.g. Realtek RTL8211 or Marvell Alaska PHY) on the board.
        ------------------------------------------------------------------------
        rgmii_txd    : out std_logic_vector(3 downto 0); -- Transmit Serial Data (double-data-rate)
        rgmii_tx_ctl : out std_logic;                    -- Transmit Control (carries TX_EN and TX_ER)
        rgmii_txc    : out std_logic;                    -- Transmit Clock output to PHY (125 MHz)
        rgmii_rxd    : in  std_logic_vector(3 downto 0); -- Receive Serial Data from PHY
        rgmii_rx_ctl : in  std_logic;                    -- Receive Control (carries RX_DV and RX_ER)
        rgmii_rxc    : in  std_logic;                    -- Receive Clock input from PHY (125 MHz)

        ------------------------------------------------------------------------
        -- MDIO (Management Data Input/Output) Serial Interface
        -- Used by the MAC to read and write control registers of the external PHY.
        ------------------------------------------------------------------------
        mdio         : inout std_logic; -- Bidirectional MDIO data line
        mdc          : out   std_logic  -- Management Data Clock generated by MAC
    );
end entity ethernet_top;

architecture rtl of ethernet_top is

    ----------------------------------------------------------------------------
    -- Clock & PLL Signals
    ----------------------------------------------------------------------------
    signal clk_fb       : std_logic; -- PLL feedback loop line
    signal gtx_clk      : std_logic; -- 125 MHz Gigabit TX reference clock (0-degree phase)
    signal gtx_clk90    : std_logic; -- 125 MHz Gigabit TX reference clock (90-degree phase shift)
    signal ref_clk_200mhz : std_logic; -- 200 MHz reference clock for IDELAYCTRL calibration
    signal s_axi_aclk   : std_logic; -- 125 MHz clock for configuration/AXI interfaces

    ----------------------------------------------------------------------------
    -- Active-Low Synchronized Resets
    ----------------------------------------------------------------------------
    signal rst_n        : std_logic; -- Active-low system reset

    ----------------------------------------------------------------------------
    -- AXI-Stream Loopback Interface Signals
    -- Loops packets received by the RX MAC back into the TX MAC.
    ----------------------------------------------------------------------------
    signal rx_axis_mac_tdata  : std_logic_vector(7 downto 0); -- Loopback write data
    signal rx_axis_mac_tvalid : std_logic;                    -- Loopback data valid
    signal rx_axis_mac_tlast  : std_logic;                    -- End-of-frame indicator
    signal rx_axis_mac_tuser  : std_logic;                    -- Bad packet error indicator
    signal tx_axis_mac_tready : std_logic;                    -- MAC ready for transmit

    -- Registered loopback signals for timing closure and register slicing
    signal tx_axis_mac_tdata_q  : std_logic_vector(7 downto 0) := (others => '0');
    signal tx_axis_mac_tvalid_q : std_logic := '0';
    signal tx_axis_mac_tlast_q  : std_logic := '0';
    signal tx_axis_mac_tuser_q  : std_logic_vector(0 downto 0) := "0";

    ----------------------------------------------------------------------------
    -- 0. Deferred Component Declaration for the TEMAC IP Core
    -- Tells the VHDL compiler the exact pin interface of the IP, allowing the
    -- target to compile successfully even before the IP netlist is generated.
    ----------------------------------------------------------------------------
    COMPONENT my_temac_core
      PORT (
        s_axi_aclk : IN STD_LOGIC;
        s_axi_resetn : IN STD_LOGIC;
        gtx_clk : IN STD_LOGIC;
        gtx_clk90 : IN STD_LOGIC;
        glbl_rstn : IN STD_LOGIC;
        rx_axi_rstn : IN STD_LOGIC;
        tx_axi_rstn : IN STD_LOGIC;
        rx_statistics_vector : OUT STD_LOGIC_VECTOR(27 DOWNTO 0);
        rx_statistics_valid : OUT STD_LOGIC;
        rx_mac_aclk : OUT STD_LOGIC;
        rx_reset : OUT STD_LOGIC;
        rx_enable : OUT STD_LOGIC;
        rx_axis_filter_tuser : OUT STD_LOGIC_VECTOR(4 DOWNTO 0);
        rx_axis_mac_tdata : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        rx_axis_mac_tvalid : OUT STD_LOGIC;
        rx_axis_mac_tlast : OUT STD_LOGIC;
        rx_axis_mac_tuser : OUT STD_LOGIC;
        tx_ifg_delay : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
        tx_statistics_vector : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
        tx_statistics_valid : OUT STD_LOGIC;
        tx_mac_aclk : OUT STD_LOGIC;
        tx_reset : OUT STD_LOGIC;
        tx_enable : OUT STD_LOGIC;
        tx_axis_mac_tdata : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
        tx_axis_mac_tvalid : IN STD_LOGIC;
        tx_axis_mac_tlast : IN STD_LOGIC;
        tx_axis_mac_tuser : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
        tx_axis_mac_tready : OUT STD_LOGIC;
        pause_req : IN STD_LOGIC;
        pause_val : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
        speedis100 : OUT STD_LOGIC;
        speedis10100 : OUT STD_LOGIC;
        rgmii_txd : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
        rgmii_tx_ctl : OUT STD_LOGIC;
        rgmii_txc : OUT STD_LOGIC;
        rgmii_rxd : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
        rgmii_rx_ctl : IN STD_LOGIC;
        rgmii_rxc : IN STD_LOGIC;
        inband_link_status : OUT STD_LOGIC;
        inband_clock_speed : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
        inband_duplex_status : OUT STD_LOGIC;
        mdio : INOUT STD_LOGIC;
        mdc : OUT STD_LOGIC;
        s_axi_awaddr : IN STD_LOGIC_VECTOR(11 DOWNTO 0);
        s_axi_awvalid : IN STD_LOGIC;
        s_axi_awready : OUT STD_LOGIC;
        s_axi_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
        s_axi_wvalid : IN STD_LOGIC;
        s_axi_wready : OUT STD_LOGIC;
        s_axi_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
        s_axi_bvalid : OUT STD_LOGIC;
        s_axi_bready : IN STD_LOGIC;
        s_axi_araddr : IN STD_LOGIC_VECTOR(11 DOWNTO 0);
        s_axi_arvalid : IN STD_LOGIC;
        s_axi_arready : OUT STD_LOGIC;
        s_axi_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
        s_axi_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
        s_axi_rvalid : OUT STD_LOGIC;
        s_axi_rready : IN STD_LOGIC;
        mac_irq : OUT STD_LOGIC 
      );
    END COMPONENT;

begin

    ----------------------------------------------------------------------------
    -- Reset Inversion
    ----------------------------------------------------------------------------
    rst_n <= not rst;

    ----------------------------------------------------------------------------
    -- 1. Clock Generation PLL (PLLE2_BASE Primitive)
    -- Generates Gigabit clocks from the 100 MHz board clock input.
    -- Inputs: 100 MHz. Feedback multiplication: 10 -> VCO = 1000 MHz.
    -- Divide-by-8 output clocks -> CLKOUT = 125 MHz.
    -- Divide-by-5 output clocks -> CLKOUT2 = 200 MHz (IDELAYCTRL ref clock).
    ----------------------------------------------------------------------------
    pll_inst : PLLE2_BASE
        generic map (
            BANDWIDTH          => "OPTIMIZED",
            CLKFBOUT_MULT      => 10,       -- VCO frequency = 100 MHz * 10 = 1000 MHz
            CLKFBOUT_PHASE     => 0.0,
            CLKIN1_PERIOD      => 10.0,     -- Input clock period is 10.0 ns (100 MHz)
            CLKOUT0_DIVIDE     => 8,        -- CLKOUT0 = 1000 / 8 = 125 MHz
            CLKOUT0_DUTY_CYCLE => 0.5,
            CLKOUT0_PHASE      => 0.0,      -- 0 degree phase clock
            CLKOUT1_DIVIDE     => 8,        -- CLKOUT1 = 1000 / 8 = 125 MHz
            CLKOUT1_DUTY_CYCLE => 0.5,
            CLKOUT1_PHASE      => 90.0,     -- 90 degree phase clock for RGMII transmit
            CLKOUT2_DIVIDE     => 5,        -- CLKOUT2 = 1000 / 5 = 200 MHz (IDELAYCTRL reference)
            CLKOUT2_DUTY_CYCLE => 0.5,
            CLKOUT2_PHASE      => 0.0,
            DIVCLK_DIVIDE      => 1
        )
        port map (
            CLKOUT0  => gtx_clk,
            CLKOUT1  => gtx_clk90,
            CLKOUT2  => ref_clk_200mhz,
            CLKOUT3  => open,
            CLKOUT4  => open,
            CLKOUT5  => open,
            CLKFBOUT => clk_fb,
            LOCKED   => open,
            CLKIN1   => clk,
            CLKFBIN  => clk_fb,
            RST      => rst,
            PWRDWN   => '0'
        );

    -- Run configuration interfaces at the 125 MHz reference speed
    s_axi_aclk <= gtx_clk;

    ----------------------------------------------------------------------------
    -- 2. IDELAYCTRL Primitive Instantiation
    -- Required in 7-Series devices to calibrate and align input delay taps (IDELAYs)
    -- against temperature, voltage, and process variations.
    ----------------------------------------------------------------------------
    delay_ctrl_inst : IDELAYCTRL
        port map (
            RDY    => open,
            REFCLK => ref_clk_200mhz, -- Standard 200 MHz calibration reference clock
            RST    => rst
        );

    ----------------------------------------------------------------------------
    -- 3. AXI-Stream Data Register Slice / Loopback Logic
    -- Latches the output packet streaming from the RX side of TEMAC and registers
    -- it before driving the inputs of the TX side of TEMAC. This prevents
    -- combinatorial feedback loops and facilitates timing closure in placement.
    ----------------------------------------------------------------------------
    loopback_proc : process(gtx_clk)
    begin
        if rising_edge(gtx_clk) then
            if rst_n = '0' then
                tx_axis_mac_tdata_q  <= (others => '0');
                tx_axis_mac_tvalid_q <= '0';
                tx_axis_mac_tlast_q  <= '0';
                tx_axis_mac_tuser_q  <= "0";
            else
                -- Accept and buffer packets when TX path is ready
                if tx_axis_mac_tready = '1' then
                    tx_axis_mac_tdata_q  <= rx_axis_mac_tdata;
                    tx_axis_mac_tvalid_q <= rx_axis_mac_tvalid;
                    tx_axis_mac_tlast_q  <= rx_axis_mac_tlast;
                    -- Loopback tuser error indicator: if '1', received frame had error
                    tx_axis_mac_tuser_q(0) <= rx_axis_mac_tuser;
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------------
    -- 4. Tri-Mode Ethernet MAC Instance
    -- Standard IEEE 802.3 compliant Media Access Controller. Handles MAC framing,
    -- preamble generation, CRC calculation, and RGMII DDR double-data-rate signaling.
    ----------------------------------------------------------------------------
    temac_inst : my_temac_core
        port map (
            --------------------------------------------------------------------
            -- Clocks & Resets
            --------------------------------------------------------------------
            s_axi_aclk           => s_axi_aclk,
            s_axi_resetn         => rst_n,
            gtx_clk              => gtx_clk,
            gtx_clk90            => gtx_clk90,
            glbl_rstn            => rst_n,
            rx_axi_rstn          => rst_n,
            tx_axi_rstn          => rst_n,

            --------------------------------------------------------------------
            -- AXI-Stream RX Data Output Channel
            -- MAC deserializes Ethernet frames and pushes them out here.
            --------------------------------------------------------------------
            rx_axis_mac_tdata    => rx_axis_mac_tdata,
            rx_axis_mac_tvalid   => rx_axis_mac_tvalid,
            rx_axis_mac_tlast    => rx_axis_mac_tlast,
            rx_axis_mac_tuser    => rx_axis_mac_tuser,

            --------------------------------------------------------------------
            -- AXI-Stream TX Data Input Channel
            -- MAC takes loopback frames and serializes them out onto RGMII lanes.
            --------------------------------------------------------------------
            tx_axis_mac_tdata    => tx_axis_mac_tdata_q,
            tx_axis_mac_tvalid   => tx_axis_mac_tvalid_q,
            tx_axis_mac_tlast    => tx_axis_mac_tlast_q,
            tx_axis_mac_tuser    => tx_axis_mac_tuser_q,
            tx_axis_mac_tready   => tx_axis_mac_tready,

            --------------------------------------------------------------------
            -- Physical RGMII Interfaces (Direct FPGA Board Pins)
            --------------------------------------------------------------------
            rgmii_txd            => rgmii_txd,
            rgmii_tx_ctl         => rgmii_tx_ctl,
            rgmii_txc            => rgmii_txc,
            rgmii_rxd            => rgmii_rxd,
            rgmii_rx_ctl         => rgmii_rx_ctl,
            rgmii_rxc            => rgmii_rxc,

            --------------------------------------------------------------------
            -- PHY Management & Statistics Channels
            --------------------------------------------------------------------
            mdio                 => mdio,
            mdc                  => mdc,
            pause_req            => '0', -- Disable pause flow control
            pause_val            => (others => '0'),
            tx_ifg_delay         => x"0C", -- Default standard inter-frame gap (12 bytes)
            
            --------------------------------------------------------------------
            -- Unused status outputs (left open)
            --------------------------------------------------------------------
            rx_statistics_vector => open,
            rx_statistics_valid  => open,
            rx_mac_aclk          => open,
            rx_reset             => open,
            rx_enable            => open,
            rx_axis_filter_tuser => open,
            tx_statistics_vector => open,
            tx_statistics_valid  => open,
            tx_mac_aclk          => open,
            tx_reset             => open,
            tx_enable            => open,
            speedis100           => open,
            speedis10100         => open,
            inband_link_status   => open,
            inband_clock_speed   => open,
            inband_duplex_status => open,
            mac_irq              => open,

            --------------------------------------------------------------------
            -- Unused AXI4-Lite configuration register access ports.
            -- Since we use hard-wired configuration defaults, we tie these off.
            --------------------------------------------------------------------
            s_axi_awaddr         => (others => '0'),
            s_axi_awvalid        => '0',
            s_axi_awready        => open,
            s_axi_wdata          => (others => '0'),
            s_axi_wvalid         => '0',
            s_axi_wready         => open,
            s_axi_bresp          => open,
            s_axi_bvalid         => open,
            s_axi_bready         => '0',
            s_axi_araddr         => (others => '0'),
            s_axi_arvalid        => '0',
            s_axi_arready        => open,
            s_axi_rdata          => open,
            s_axi_rresp          => open,
            s_axi_rvalid         => open,
            s_axi_rready         => '0'
        );

end architecture rtl;
