--------------------------------------------------------------------------------
-- Company: hdlfactory.com
-- Engineer: Automated Assistant with Human Supervision
-- 
-- Create Date: Friday, June 19, 2026
-- Design Name: xdma_top
-- Module Name: xdma_top - rtl
-- Project Name: PCI Express XDMA Core Integration Test
-- Target Devices: xc7a200tfbg484-2 (Artix-7)
-- Tool Versions: Vivado 2025.2
-- 
-- Description: 
-- This is a top-level VHDL design that instantiates the Xilinx PCIe XDMA Core
-- (DMA/Bridge Subsystem for PCI Express) and integrates it with a local 4KB
-- dual-port Block RAM (BRAM). This provides an end-to-end verifiable loopback
-- interface where the host PC can write and read from BRAM over PCIe JTAG/DMA.
--
-- Dependencies: 
-- - my_xdma_core: Generated PCIe XDMA Core IP
-- - IBUFDS_GTE2: Xilinx primitive for differential MGT reference clocks
-- 
-- Revision:
-- Revision 0.04 - Switched to deferred VHDL component instantiation for compile compatibility.
-- Additional Comments:
-- Copious comments describing the Top Level API elements have been added.
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- unisim library contains Xilinx device primitives like IBUFDS_GTE2
library unisim;
use unisim.vcomponents.all;

entity xdma_top is
    port (
        ------------------------------------------------------------------------
        -- Differential PCIe Reference Clock Inputs (MGT Reference Clocks)
        -- These are dedicated differential clock inputs routed directly to 
        -- the MGT Gig_Transceiver block on the Artix-7 device.
        ------------------------------------------------------------------------
        sys_clk_p    : in  std_logic; -- Differential PCIe Reference Clock Plus
        sys_clk_n    : in  std_logic; -- Differential PCIe Reference Clock Minus

        ------------------------------------------------------------------------
        -- System Reset (Active Low)
        -- This reset is asserted by the host PC's PCIe slot reset line (PERST#).
        ------------------------------------------------------------------------
        sys_rst_n    : in  std_logic; -- PCIe Slot Reset (Active Low, PERST#)

        ------------------------------------------------------------------------
        -- PCIe Lane 0 Differential Receiver Pins
        -- Since this is configured as a PCIe 1-lane (X1) setup, only Lane 0 is used.
        ------------------------------------------------------------------------
        pci_exp_rxp  : in  std_logic_vector(0 downto 0); -- PCIe RX Lane 0 Plus
        pci_exp_rxn  : in  std_logic_vector(0 downto 0); -- PCIe RX Lane 0 Minus

        ------------------------------------------------------------------------
        -- PCIe Lane 0 Differential Transmitter Pins
        -- Dedicated Gigabit Transceiver serial lanes sending packets back to Host.
        ------------------------------------------------------------------------
        pci_exp_txp  : out std_logic_vector(0 downto 0); -- PCIe TX Lane 0 Plus
        pci_exp_txn  : out std_logic_vector(0 downto 0)  -- PCIe TX Lane 0 Minus
    );
end entity xdma_top;

architecture rtl of xdma_top is

    ----------------------------------------------------------------------------
    -- Clock & Reset Signals
    ----------------------------------------------------------------------------
    signal sys_clk     : std_logic; -- Single-ended reference clock output from IBUFDS
    signal axi_aclk    : std_logic; -- AXI clock generated by the PCIe core (125 MHz)
    signal axi_aresetn : std_logic; -- AXI active-low reset generated by the core

    ----------------------------------------------------------------------------
    -- AXI Master Write Address Channel (M_AXI_AW)
    -- Generated by the XDMA core to declare write targets.
    ----------------------------------------------------------------------------
    signal m_axi_awaddr   : std_logic_vector(63 downto 0); -- Write address (64-bit)
    signal m_axi_awlen    : std_logic_vector(7 downto 0);  -- Burst length (0-255)
    signal m_axi_awsize   : std_logic_vector(2 downto 0);  -- Burst size (bytes per transfer)
    signal m_axi_awburst  : std_logic_vector(1 downto 0);  -- Burst type (Incr/Fixed)
    signal m_axi_awvalid  : std_logic;                     -- Write address valid
    signal m_axi_awready  : std_logic;                     -- BRAM ready for write addr

    ----------------------------------------------------------------------------
    -- AXI Master Write Data Channel (M_AXI_W)
    -- Carries the actual data payload to be written to memory.
    ----------------------------------------------------------------------------
    signal m_axi_wdata    : std_logic_vector(63 downto 0); -- Write data (64-bit)
    signal m_axi_wstrb    : std_logic_vector(7 downto 0);  -- Write byte lane strobe
    signal m_axi_wlast    : std_logic;                     -- Indication of last burst beat
    signal m_axi_wvalid   : std_logic;                     -- Write data valid
    signal m_axi_wready   : std_logic;                     -- BRAM ready for write data

    ----------------------------------------------------------------------------
    -- AXI Master Write Response Channel (M_AXI_B)
    -- Tells the XDMA core whether the write transaction succeeded.
    ----------------------------------------------------------------------------
    signal m_axi_bresp    : std_logic_vector(1 downto 0);  -- Write response (00 = OKAY)
    signal m_axi_bvalid   : std_logic;                     -- Write response valid
    signal m_axi_bready   : std_logic;                     -- Core ready for response

    ----------------------------------------------------------------------------
    -- AXI Master Read Address Channel (M_AXI_AR)
    -- Generated by the XDMA core to declare read targets.
    ----------------------------------------------------------------------------
    signal m_axi_araddr   : std_logic_vector(63 downto 0); -- Read address (64-bit)
    signal m_axi_arvalid  : std_logic;                     -- Read address valid
    signal m_axi_arready  : std_logic;                     -- BRAM ready for read addr

    ----------------------------------------------------------------------------
    -- AXI Master Read Data Channel (M_AXI_R)
    -- Carries read data back to the XDMA core to be routed to Host PC.
    ----------------------------------------------------------------------------
    signal m_axi_rdata    : std_logic_vector(63 downto 0); -- Read data (64-bit)
    signal m_axi_rresp    : std_logic_vector(1 downto 0);  -- Read response (00 = OKAY)
    signal m_axi_rlast    : std_logic;                     -- Indication of last read beat
    signal m_axi_rvalid   : std_logic;                     -- Read data valid
    signal m_axi_rready   : std_logic;                     -- Core ready for read data

    ----------------------------------------------------------------------------
    -- 4KB Inferred Dual-Port Block RAM (BRAM)
    -- 4096 bytes / 8 bytes (64-bit words) = 512 depth of memory.
    ----------------------------------------------------------------------------
    type ram_type is array (0 to 511) of std_logic_vector(63 downto 0);
    signal ram : ram_type := (others => (others => '0'));

    -- Address signals decoded from 64-bit AXI addresses
    signal wr_addr : integer range 0 to 511 := 0;
    signal rd_addr : integer range 0 to 511 := 0;

    ----------------------------------------------------------------------------
    -- 0. Deferred Component Declaration for the XDMA IP Core
    -- Tells the VHDL compiler the exact pin interface of the IP, allowing the
    -- target to compile successfully even before the IP netlist is generated.
    ----------------------------------------------------------------------------
    COMPONENT my_xdma_core
      PORT (
        sys_clk : IN STD_LOGIC;
        sys_rst_n : IN STD_LOGIC;
        pci_exp_rxp : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
        pci_exp_rxn : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
        pci_exp_txp : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
        pci_exp_txn : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
        axi_aclk : OUT STD_LOGIC;
        axi_aresetn : OUT STD_LOGIC;
        usr_irq_req : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
        m_axi_awaddr : OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
        m_axi_awlen : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        m_axi_awsize : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
        m_axi_awburst : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
        m_axi_awvalid : OUT STD_LOGIC;
        m_axi_awready : IN STD_LOGIC;
        m_axi_wdata : OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
        m_axi_wstrb : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        m_axi_wlast : OUT STD_LOGIC;
        m_axi_wvalid : OUT STD_LOGIC;
        m_axi_wready : IN STD_LOGIC;
        m_axi_bid : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
        m_axi_bresp : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
        m_axi_bvalid : IN STD_LOGIC;
        m_axi_bready : OUT STD_LOGIC;
        m_axi_araddr : OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
        m_axi_rdata : IN STD_LOGIC_VECTOR(63 DOWNTO 0);
        m_axi_rresp : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
        m_axi_rlast : IN STD_LOGIC;
        m_axi_rvalid : IN STD_LOGIC;
        m_axi_rready : OUT STD_LOGIC;
        m_axi_rid : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
        m_axi_arready : IN STD_LOGIC;
        m_axi_arvalid : OUT STD_LOGIC;
        cfg_mgmt_byte_enable : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
        cfg_mgmt_addr : IN STD_LOGIC_VECTOR(18 DOWNTO 0);
        cfg_mgmt_write_data : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
        cfg_mgmt_write : IN STD_LOGIC;
        cfg_mgmt_read : IN STD_LOGIC;
        cfg_mgmt_type1_cfg_reg_access : IN STD_LOGIC
      );
    END COMPONENT;

begin

    ----------------------------------------------------------------------------
    -- 1. PCIe Reference Clock Buffer (IBUFDS_GTE2 Primitive)
    -- Convert the external PCIe slots differential clock pins (sys_clk_p/n)
    -- into the single-ended sys_clk required by the PCIe Hard IP block.
    ----------------------------------------------------------------------------
    sys_clk_buf : IBUFDS_GTE2
        port map (
            O     => sys_clk,     -- Single-ended clock output (100 MHz)
            ODIV2 => open,        -- Unused divide-by-2 clock output
            I     => sys_clk_p,   -- MGT Reference clock input plus
            IB    => sys_clk_n,   -- MGT Reference clock input minus
            CEB   => '0'          -- Clock buffer enable (Active Low)
        );

    ----------------------------------------------------------------------------
    -- 2. XDMA Core Instantiation
    -- Bridges PCIe packets to the local AXI system-on-chip interfaces.
    ----------------------------------------------------------------------------
    xdma_inst : my_xdma_core
        port map (
            --------------------------------------------------------------------
            -- Clocks, Resets & Serial Lanes
            --------------------------------------------------------------------
            sys_clk        => sys_clk,
            sys_rst_n      => sys_rst_n,
            pci_exp_rxp    => pci_exp_rxp,
            pci_exp_rxn    => pci_exp_rxn,
            pci_exp_txp    => pci_exp_txp,
            pci_exp_txn    => pci_exp_txn,
            axi_aclk       => axi_aclk,
            axi_aresetn    => axi_aresetn,

            --------------------------------------------------------------------
            -- AXI Write Channels
            -- AW (Write Address), W (Write Data), B (Write Response)
            --------------------------------------------------------------------
            m_axi_awaddr   => m_axi_awaddr,
            m_axi_awlen    => m_axi_awlen,
            m_axi_awsize   => m_axi_awsize,
            m_axi_awburst  => m_axi_awburst,
            m_axi_awvalid  => m_axi_awvalid,
            m_axi_awready  => m_axi_awready,
            m_axi_wdata    => m_axi_wdata,
            m_axi_wstrb    => m_axi_wstrb,
            m_axi_wlast    => m_axi_wlast,
            m_axi_wvalid   => m_axi_wvalid,
            m_axi_wready   => m_axi_wready,
            m_axi_bid      => "0000",
            m_axi_bresp    => m_axi_bresp,
            m_axi_bvalid   => m_axi_bvalid,
            m_axi_bready   => m_axi_bready,

            --------------------------------------------------------------------
            -- AXI Read Channels
            -- AR (Read Address), R (Read Data)
            --------------------------------------------------------------------
            m_axi_araddr   => m_axi_araddr,
            m_axi_rdata    => m_axi_rdata,
            m_axi_rresp    => m_axi_rresp,
            m_axi_rlast    => m_axi_rlast,
            m_axi_rvalid   => m_axi_rvalid,
            m_axi_rready   => m_axi_rready,
            m_axi_rid      => "0000",
            m_axi_arready  => m_axi_arready,
            m_axi_arvalid  => m_axi_arvalid,

            --------------------------------------------------------------------
            -- Irq Ports Tying Off
            --------------------------------------------------------------------
            usr_irq_req    => "0",

            --------------------------------------------------------------------
            -- Configuration Management Inputs (Tied off to '0')
            -- Crucial tie-off to prevent Vivado's logic trimming / optimization
            -- from removing required hard block inputs during opt_design.
            --------------------------------------------------------------------
            cfg_mgmt_byte_enable          => (others => '0'),
            cfg_mgmt_addr                 => (others => '0'),
            cfg_mgmt_write_data           => (others => '0'),
            cfg_mgmt_write                => '0',
            cfg_mgmt_read                 => '0',
            cfg_mgmt_type1_cfg_reg_access => '0'
        );

    ----------------------------------------------------------------------------
    -- 3. Simple AXI Dual-Port Block RAM Controller State Machine
    -- Decodes incoming transactions on the axi_aclk clock domain.
    ----------------------------------------------------------------------------
    wr_clk_process : process(axi_aclk)
    begin
        if rising_edge(axi_aclk) then
            -- Reset state: Declare memory ready for transactions
            if axi_aresetn = '0' then
                m_axi_awready <= '1';
                m_axi_wready  <= '1';
                m_axi_bvalid  <= '0';
                m_axi_arready <= '1';
                m_axi_rvalid  <= '0';
            else
                ----------------------------------------------------------------
                -- Write transaction decode
                ----------------------------------------------------------------
                -- Capture write address (using 3-bit shift for 64-bit alignment)
                if m_axi_awvalid = '1' then
                    wr_addr <= to_integer(unsigned(m_axi_awaddr(11 downto 3)));
                end if;

                -- Write transaction execution
                if m_axi_wvalid = '1' then
                    ram(wr_addr) <= m_axi_wdata;
                    m_axi_bvalid <= '1';
                else
                    m_axi_bvalid <= '0';
                end if;

                ----------------------------------------------------------------
                -- Read transaction decode
                ----------------------------------------------------------------
                -- Capture read address and trigger read valid handshake
                if m_axi_arvalid = '1' then
                    rd_addr      <= to_integer(unsigned(m_axi_araddr(11 downto 3)));
                    m_axi_rvalid <= '1';
                else
                    m_axi_rvalid <= '0';
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------------
    -- AXI Response Mapping
    ----------------------------------------------------------------------------
    m_axi_rdata <= ram(rd_addr); -- Dual-port continuous memory read output
    m_axi_rresp <= "00";         -- OKAY read status
    m_axi_rlast <= '1';          -- Always declare lastbeat for single transfers
    m_axi_bresp <= "00";         -- OKAY write status

end architecture rtl;
