"""Vivado IP generation rule."""

load("//internal:defines.bzl",
    "VIVADO_VERSION", "CONTAINER", "VIVADO_PATH",
    "DOCKER_RUN_SCRIPT_ATTRS",
    _script_cmd = "script_cmd",
)
load("//internal:providers.bzl",
    "VivadoLibraryProvider",
)

def _vivado_ip_impl(ctx):
    """Implementation for the vivado_ip rule.

    Args:
      ctx: The rule context.

    Returns:
      A list of providers, including DefaultInfo and VivadoLibraryProvider.
    """
    name = ctx.attr.name
    module_name = ctx.attr.module_name or name
    vlnv = ctx.attr.vlnv
    part = ctx.attr.part

    # Outputs
    # We want to capture the generated IP directory.
    ip_output_dir = ctx.actions.declare_directory("{}.ip_gen".format(name))
    # And the compiled library directory for simulation.
    library_output_dir = ctx.actions.declare_directory("{}.hdlib".format(name))

    outputs = [ip_output_dir, library_output_dir]

    # Generate TCL script
    tcl_script = ctx.actions.declare_file("{}.gen_ip.tcl".format(name))

    config_commands = ""
    if ctx.attr.config:
        config_list = []
        for k, v in ctx.attr.config.items():
            config_list.append("CONFIG.{} {{{}}}".format(k, v))
        config_commands = "set_property -dict [list {}] [get_ips {}]".format(
            " ".join(config_list), module_name)

    ctx.actions.expand_template(
        output = tcl_script,
        template = ctx.file._template,
        substitutions = {
            "{{COMMENT}}": "Generated by Bazel",
            "{{PART}}": part,
            "{{VLNV}}": vlnv,
            "{{MODULE_NAME}}": module_name,
            "{{CONFIG_COMMANDS}}": config_commands,
        },
    )

    # Prepare to run Vivado
    docker_run = ctx.executable._script
    cache_dir = ctx.actions.declare_directory("_vivado_ip.cache.{}".format(name))
    work_dir = ctx.actions.declare_directory("_vivado_ip.work.{}".format(name))
    outputs += [cache_dir, work_dir]

    script = _script_cmd(
      docker_run.path,
      work_dir.path,
      cache_dir.path,
      envs="",
      mounts="",
      freeargs=[
        "--net=host",
        "-e", "HOME=/work",
      ],
    )

    log_file = ctx.actions.declare_file("{}.log".format(name))
    outputs += [log_file]

    # Bash command script
    shell_script = ctx.actions.declare_file("{}.sh".format(name))
    ctx.actions.expand_template(
        output = shell_script,
        template = ctx.file._shell_template,
        substitutions = {
            "{SCRIPT}": script,
            "{VIVADO_PATH}": VIVADO_PATH,
            "{TCL_SCRIPT}": tcl_script.path,
            "{LOG}": log_file.path,
            "{MODULE_NAME}": module_name,
            "{IP_OUTPUT_DIR}": ip_output_dir.path,
            "{LIBRARY_OUTPUT_DIR}": library_output_dir.path,
        },
    )

    ctx.actions.run_shell(
        progress_message = "Vivado generate IP \"{}\"".format(module_name),
        inputs = [tcl_script, docker_run, shell_script],
        outputs = outputs,
        tools = [docker_run],
        mnemonic = "VivadoIP",
        command = "bash {}".format(shell_script.path),
    )
    return [
        DefaultInfo(files=depset([ip_output_dir, library_output_dir])),
        VivadoLibraryProvider(
            name=module_name,
            files=[ip_output_dir],
            hdrs=depset([]),
            includes=depset([]),
            deps=depset([]),
            deps_names=depset([module_name]),
            library_dir=library_output_dir,
            unisims_libs=False,
        ),
    ]

vivado_ip = rule(
    implementation = _vivado_ip_impl,
    attrs = DOCKER_RUN_SCRIPT_ATTRS | {
        "vlnv": attr.string(
            mandatory = True,
            doc = "The VLNV of the IP.",
        ),
        "module_name": attr.string(
            doc = "The name of the IP module. Defaults to target name.",
        ),
        "config": attr.string_dict(
            doc = "Configuration properties for the IP.",
        ),
        "part": attr.string(
            mandatory = True,
            doc = "The target FPGA part.",
        ),
        "_template": attr.label(
            default = Label("//build/vivado:generate_ip.tcl.template"),
            allow_single_file = True,
        ),
        "_shell_template": attr.label(
            default = Label("//internal:vivado_ip.sh.tpl"),
            allow_single_file = True,
        ),
    },
)
