"""Vivado IP generation rule."""

load(
    "//internal:defines.bzl",
    "DOCKER_RUN_SCRIPT_ATTRS",
    "VIVADO_TOOLCHAIN_TYPE",
    _script_cmd = "script_cmd",
    _vivado_config = "vivado_config",
)
load(
    "//internal:providers.bzl",
    "VivadoLibraryProvider",
)

def _vivado_ip_impl(ctx):
    """Implementation for the vivado_ip rule.

    Args:
      ctx: The rule context.

    Returns:
      A list of providers, including DefaultInfo and VivadoLibraryProvider.
    """
    config = _vivado_config(ctx)
    name = ctx.attr.name
    module_name = ctx.attr.module_name or name
    vlnv = ctx.attr.vlnv
    part = ctx.attr.part

    # Outputs
    # We want to capture the generated IP directory.
    ip_output_dir = ctx.actions.declare_directory("{}.ip_gen".format(name))

    # And the compiled library directory for simulation.
    library_output_dir = ctx.actions.declare_directory("{}.hdlib".format(name))

    outputs = [ip_output_dir, library_output_dir]

    # Generate TCL script
    tcl_script = ctx.actions.declare_file("{}.gen_ip.tcl".format(name))

    # Files the configuration names, MIG's project file say: a value
    # `data:<name>` names a file in `data`, which is copied into the
    # IP's own directory before the configuration is set, and the value
    # becomes the bare name, which is where and how such an IP reads it.
    data_files = []
    for target in ctx.attr.data:
        data_files += target.files.to_list()
    data_copies = []
    config_commands = ""
    if ctx.attr.config:
        config_list = []
        for k, v in ctx.attr.config.items():
            if v.startswith("data:"):
                wanted = v[len("data:"):]
                found = [f for f in data_files if f.basename == wanted]
                if len(found) != 1:
                    fail("config %s names %s, which `data` must hold exactly once" % (k, wanted))
                config_list.append("CONFIG.{} {{{}}}".format(k, wanted))
                data_copies.append(
                    "file copy -force {{{}}} [get_property IP_DIR [get_ips {}]]".format(
                        found[0].path,
                        module_name,
                    ),
                )
            else:
                config_list.append("CONFIG.{} {{{}}}".format(k, v))
        config_commands = "\n    ".join(data_copies + [
            "set_property -dict [list {}] [get_ips {}]".format(
                " ".join(config_list),
                module_name,
            ),
        ])

    # The IP's example design, kept beside the IP when asked for: its
    # testbench and models are what a simulation of the IP against a
    # partner needs, a root port for a PCIe endpoint say, and Vivado
    # writes them only into an example project.
    example_commands = ""
    if ctx.attr.example_design:
        example_commands = (
            "open_example_project -force -dir {0}.example [get_ips {0}]"
        ).format(module_name)
    ctx.actions.expand_template(
        output = tcl_script,
        template = ctx.file._template,
        substitutions = {
            "{{COMMENT}}": "Generated by Bazel",
            "{{PART}}": part,
            "{{VLNV}}": vlnv,
            "{{MODULE_NAME}}": module_name,
            "{{CONFIG_COMMANDS}}": config_commands,
            "{{EXAMPLE_DESIGN}}": example_commands,
        },
    )

    # Prepare to run Vivado
    runner = config.runner
    cache_dir = ctx.actions.declare_directory("_vivado_ip.cache.{}".format(name))
    work_dir = ctx.actions.declare_directory("_vivado_ip.work.{}".format(name))
    outputs += [cache_dir, work_dir]

    script = _script_cmd(
        runner.executable.path,
        work_dir.path,
        cache_dir.path,
        envs = "",
        mounts = "",
        freeargs = [
            "--net=host",
            "-e",
            "HOME=/work",
        ],
        container = config.container,
    )

    log_file = ctx.actions.declare_file("{}.log".format(name))
    outputs += [log_file]

    # Bash command script
    shell_script = ctx.actions.declare_file("{}.sh".format(name))
    ctx.actions.expand_template(
        output = shell_script,
        template = ctx.file._shell_template,
        substitutions = {
            "{SCRIPT}": script,
            "{VIVADO_PATH}": config.vivado_path,
            "{TCL_SCRIPT}": tcl_script.path,
            "{LOG}": log_file.path,
            "{MODULE_NAME}": module_name,
            "{IP_OUTPUT_DIR}": ip_output_dir.path,
            "{LIBRARY_OUTPUT_DIR}": library_output_dir.path,
        },
    )

    ctx.actions.run_shell(
        progress_message = "Vivado generate IP \"{}\"".format(module_name),
        inputs = [tcl_script, shell_script] + data_files,
        outputs = outputs,
        tools = [runner],
        mnemonic = "VivadoIP",
        command = "bash {}".format(shell_script.path),
    )
    return [
        DefaultInfo(files = depset([ip_output_dir, library_output_dir])),
        VivadoLibraryProvider(
            name = module_name,
            files = [ip_output_dir],
            hdrs = depset([]),
            includes = depset([]),
            deps = depset([]),
            # The names of the libraries in `deps`, which an IP has none
            # of; its own name is `name`, as a library's is. Naming
            # itself here made a library that depends on the IP take
            # it for one already reached through another dependency,
            # so no test elaborating that library was given the IP's.
            deps_names = depset([]),
            library_dir = library_output_dir,
            unisims_libs = False,
        ),
    ]

vivado_ip = rule(
    implementation = _vivado_ip_impl,
    toolchains = [VIVADO_TOOLCHAIN_TYPE],
    attrs = DOCKER_RUN_SCRIPT_ATTRS | {
        "vlnv": attr.string(
            mandatory = True,
            doc = "The VLNV of the IP.",
        ),
        "module_name": attr.string(
            doc = "The name of the IP module. Defaults to target name.",
        ),
        "config": attr.string_dict(
            doc = "Configuration properties for the IP.",
        ),
        "part": attr.string(
            mandatory = True,
            doc = "The target FPGA part.",
        ),
        "example_design": attr.bool(
            default = False,
            doc = "Open the IP's example design as well, and keep its " +
                  "imported sources, the testbench and the models Vivado " +
                  "ships for the IP, under `<name>.ip_gen/example/imports`.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Files the configuration names: a `config` value of the " +
                  "form `data:<name>` is replaced by the path of the file " +
                  "of that name here, for an IP configured from a file, " +
                  "as MIG is from its project file.",
        ),
        "_template": attr.label(
            default = Label("//build/vivado:generate_ip.tcl.template"),
            allow_single_file = True,
        ),
        "_shell_template": attr.label(
            default = Label("//internal:vivado_ip.sh.tpl"),
            allow_single_file = True,
        ),
    },
)
