name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: "sudo apt-get install -y build-essential automake autoconf flex check llvm-dev pkg-config zlib1g-dev libdw-dev libffi-dev"
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 5.1.0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build everything
        run: "bazel build //..."
      - name: Build HDL
        run: "bazel build //build/tests/hdl-toolchain/..."
      - name: Build muntjac_core example
        run: "bazel build //third_party/muntjac:muntjac_core"
      - name: Build muntjac GCC toolchain example
        run: "bazel build //build/tests/muntjac-gcc-toolchain/..."
      - name: Build NVC
        run: "bazel build //build/tests/nvc-toolchain/..."
